// Diesel schema for `users` table
// Generated by hand to match the migration

diesel::table! {
    users (id) {
        id -> Integer,
        username -> Text,
        password_hash -> Text,
        role -> Text,
        created_at -> BigInt,
    }
}
